import {FormEvent,useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {contentApi,operationsApi} from "../../services/api";
import {DataTable,Loading,Metric,MiniChart,Page,StatusBadge} from "../../components/ui";

const useData=(key:string,fn:()=>Promise<any>)=>useQuery({queryKey:[key],queryFn:fn});
export function NetworkDashboard(){const network=useData("network",contentApi.network),incidents=useData("incidents",operationsApi.incidents);const rows=network.data??[];return <Page title="Şəbəkə dashboard" subtitle="Organisation daxilində bütün filialların müqayisəli görünüşü"><div className="grid"><Metric label="Filial" value={rows.length}/><Metric label="Açıq incident" value={rows.reduce((s:number,x:any)=>s+x.open_incidents,0)}/><Metric label="Yüksək risk" value={rows.reduce((s:number,x:any)=>s+x.high_risk,0)}/><Metric label="Orta score" value={rows.length?Math.round(rows.reduce((s:number,x:any)=>s+x.score,0)/rows.length):0}/></div><div className="content spaced"><section className="card"><h2>Smart Store Score</h2><MiniChart rows={rows} labelKey="branch" valueKey="score"/></section><section className="card"><h2>Mənbələr</h2><MiniChart rows={Object.entries((incidents.data??[]).reduce((a:any,x:any)=>({...a,[x.source]:(a[x.source]??0)+1}),{})).map(([source,count])=>({source,count}))} labelKey="source" valueKey="count"/></section></div></Page>}
export function BranchComparisonPage(){const q=useData("network",contentApi.network);return <Page title="Filial müqayisəsi" subtitle="Risk, audit keyfiyyəti və score"><section className="card"><DataTable rows={q.data??[]} columns={[{key:"branch",label:"Filial"},{key:"open_incidents",label:"Açıq"},{key:"high_risk",label:"Yüksək risk"},{key:"quality_flags",label:"Flag"},{key:"score",label:"Score",render:r=><b>{r.score}/100</b>}]}/></section></Page>}
export function OperationalAnalyticsPage(){const incidents=useData("incidents",operationsApi.incidents),audits=useData("audits",operationsApi.audits);const sources=Object.entries((incidents.data??[]).reduce((a:any,x:any)=>({...a,[x.source]:(a[x.source]??0)+1}),{})).map(([name,value])=>({name,value}));const statuses=Object.entries((audits.data??[]).reduce((a:any,x:any)=>({...a,[x.status]:(a[x.status]??0)+1}),{})).map(([name,value])=>({name,value}));return <Page title="Əməliyyat analitikası" subtitle="Incident mənbələri və audit statusları"><div className="content"><section className="card"><h2>Incident mənbələri</h2><MiniChart rows={sources} labelKey="name" valueKey="value"/></section><section className="card"><h2>Audit statusları</h2><MiniChart rows={statuses} labelKey="name" valueKey="value"/></section></div></Page>}
export function ScoreRankingPage(){const q=useData("network",contentApi.network);return <Page title="Smart Store Score sıralaması" subtitle="İzah edilə bilən daxili əməliyyat göstəricisi"><section className="card"><DataTable rows={[...(q.data??[])].sort((a,b)=>b.score-a.score)} columns={[{key:"rank",label:"#",render:(_,i?:any)=>i},{key:"branch",label:"Filial"},{key:"score",label:"Score",render:r=><StatusBadge value={`${r.score}/100`}/>},{key:"open_incidents",label:"Açıq"},{key:"quality_flags",label:"Audit flagı"}]}/></section></Page>}

function Resource({title,subtitle,keyName,fn,columns}:{title:string;subtitle:string;keyName:string;fn:()=>Promise<any[]>;columns:any[]}){const q=useData(keyName,fn);return <Page title={title} subtitle={subtitle}><section className="card">{q.isLoading?<Loading/>:<DataTable rows={q.data??[]} columns={columns}/>}</section></Page>}
export const BranchesPage=()=> <Resource title="Filiallar" subtitle="Organisation filial kataloqu" keyName="branches" fn={operationsApi.branches} columns={[{key:"name",label:"Filial"},{key:"address",label:"Ünvan"},{key:"hours",label:"İş saatı"},{key:"is_open",label:"Status",render:(r:any)=><StatusBadge value={r.is_open?"OPEN":"CLOSED"}/>}]}/>;
export const StaffOverviewPage=()=> <Resource title="Staff overview" subtitle="Bütün organisation əməkdaşları" keyName="staff" fn={operationsApi.staff} columns={[{key:"full_name",label:"Ad"},{key:"email",label:"E-poçt"},{key:"branch_id",label:"Filial"},{key:"is_active",label:"Aktiv",render:(r:any)=>r.is_active?"Bəli":"Xeyr"}]}/>;
export const CameraOverviewPage=()=> <Resource title="Kamera overview" subtitle="Hybrid pipeline telemetry; controlled MP4 RTSP deyil" keyName="vision" fn={operationsApi.visionHealth} columns={[{key:"name",label:"Kamera"},{key:"source_type",label:"Mənbə"},{key:"source_active",label:"Status",render:(r:any)=><StatusBadge value={r.source_active?"ACTIVE":"ERROR"}/>},{key:"approximate_fps",label:"Təxmini FPS"},{key:"rules",label:"Engine / rule",render:(r:any)=>r.rules?.map((x:any)=>`${x.rule_type}: ${x.detection_engine} [${x.current_state}]`).join("; ")||"—"},{key:"processing_error",label:"Xəta"}]}/>;

export function NewsPage(){const client=useQueryClient(),q=useData("news",contentApi.news),[form,setForm]=useState({title_az:"",title_en:"",summary_az:"",summary_en:"",image_url:"/assets/news-market.svg",branch_id:null}),mutation=useMutation({mutationFn:()=>contentApi.createNews(form),onSuccess:()=>client.invalidateQueries({queryKey:["news"]})});return <Page title="Xəbər idarəetməsi" subtitle="Mobil tətbiq üçün AZ/EN xəbərlər"><div className="content"><CrudForm title="Yeni xəbər" form={form} setForm={setForm} onSubmit={()=>mutation.mutate()}/><section className="card"><DataTable rows={q.data??[]} columns={[{key:"title_az",label:"Başlıq AZ"},{key:"title_en",label:"Başlıq EN"},{key:"published_at",label:"Tarix",render:r=>new Date(r.published_at).toLocaleDateString("az-AZ")},{key:"actions",label:"Əməliyyat",render:r=><div className="inline"><EditButton run={()=>{const title=prompt("AZ başlıq",r.title_az);return title?contentApi.updateNews(r.id,{...r,title_az:title}):Promise.resolve(r)}} invalidate="news"/><DeleteButton run={()=>contentApi.deleteNews(r.id)} invalidate="news"/></div>}]}/></section></div></Page>}
export function ProductsPage(){const client=useQueryClient(),q=useData("products",contentApi.products),[form,setForm]=useState({name:"",brand:"",barcode:"",category:"Food",price:"",discount_price:"",image_url:"/assets/product.svg"}),mutation=useMutation({mutationFn:()=>contentApi.createProduct({...form,price:Number(form.price),discount_price:form.discount_price?Number(form.discount_price):null}),onSuccess:()=>client.invalidateQueries({queryKey:["products"]})});return <Page title="Məhsul CRUD" subtitle="Organisation məhsul kataloqu"><div className="content"><CrudForm title="Yeni məhsul" form={form} setForm={setForm} onSubmit={()=>mutation.mutate()}/><section className="card"><DataTable rows={q.data??[]} columns={[{key:"name",label:"Məhsul"},{key:"barcode",label:"Barkod"},{key:"category",label:"Kateqoriya"},{key:"price",label:"Qiymət",render:r=>`${r.price.toFixed(2)} ₼`},{key:"actions",label:"Əməliyyat",render:r=><div className="inline"><EditButton run={()=>{const name=prompt("Məhsul adı",r.name);return name?contentApi.updateProduct(r.id,{...r,name}):Promise.resolve(r)}} invalidate="products"/><DeleteButton run={()=>contentApi.deleteProduct(r.id)} invalidate="products"/></div>}]}/></section></div></Page>}
export function CategoriesPage(){const q=useData("categories",contentApi.categories),[name,setName]=useState(""),client=useQueryClient(),mutation=useMutation({mutationFn:()=>contentApi.createCategory(name),onSuccess:()=>{setName("");client.invalidateQueries({queryKey:["categories"]})}});return <Page title="Kateqoriya CRUD" subtitle="Məhsul filterlərinin idarə edilməsi"><div className="content"><form className="card form" onSubmit={e=>{e.preventDefault();mutation.mutate()}}><h2>Yeni kateqoriya</h2><label className="field">Ad<input value={name} onChange={e=>setName(e.target.value)}/></label><button className="btn">Yarat</button></form><section className="card"><DataTable rows={q.data??[]} columns={[{key:"name",label:"Kateqoriya"},{key:"delete",label:"",render:r=><DeleteButton run={()=>contentApi.deleteCategory(r.id)} invalidate="categories"/>}]}/></section></div></Page>}
export function PricesPage(){const branches=useData("branches",operationsApi.branches),products=useData("products",contentApi.products),prices=useData("prices",contentApi.prices),client=useQueryClient(),[form,setForm]=useState({branch_id:"",product_id:"",price:"",previous_price:"",available:true}),mutation=useMutation({mutationFn:()=>contentApi.setPrice({...form,price:Number(form.price),previous_price:form.previous_price?Number(form.previous_price):null}),onSuccess:()=>client.invalidateQueries({queryKey:["prices"]})});return <Page title="Filial qiymətləri CRUD" subtitle="Məhsulun filial üzrə qiymət və mövcudluğu"><div className="content"><form className="card form" onSubmit={e=>{e.preventDefault();mutation.mutate()}}><h2>Qiymət təyin et / yenilə</h2><Select label="Filial" value={form.branch_id} options={branches.data??[]} onChange={value=>setForm({...form,branch_id:value})}/><Select label="Məhsul" value={form.product_id} options={products.data??[]} onChange={value=>setForm({...form,product_id:value})}/><label className="field">Qiymət<input type="number" step=".01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><button className="btn">Yadda saxla</button></form><section className="card"><DataTable rows={prices.data??[]} columns={[{key:"branch_id",label:"Filial ID"},{key:"product_id",label:"Məhsul ID"},{key:"price",label:"Qiymət"},{key:"available",label:"Mövcud"},{key:"delete",label:"",render:r=><DeleteButton run={()=>contentApi.deletePrice(r.id)} invalidate="prices"/>}]}/></section></div></Page>}
export function CampaignsPage(){const q=useData("campaigns",contentApi.campaigns),client=useQueryClient(),[form,setForm]=useState({title:"",description:"",starts_on:"",ends_on:"",published:true}),mutation=useMutation({mutationFn:()=>contentApi.createCampaign(form),onSuccess:()=>client.invalidateQueries({queryKey:["campaigns"]})});return <Page title="Kampaniya CRUD" subtitle="Endirim kampaniyaları və tarix aralığı"><div className="content"><CrudForm title="Yeni kampaniya" form={form} setForm={setForm} onSubmit={()=>mutation.mutate()}/><section className="card"><DataTable rows={q.data??[]} columns={[{key:"title",label:"Kampaniya"},{key:"starts_on",label:"Başlanğıc"},{key:"ends_on",label:"Son"},{key:"published",label:"Status",render:r=><StatusBadge value={r.published?"PUBLISHED":"DRAFT"}/>},{key:"actions",label:"Əməliyyat",render:r=><div className="inline"><EditButton run={()=>{const title=prompt("Kampaniya adı",r.title);return title?contentApi.updateCampaign(r.id,{...r,title}):Promise.resolve(r)}} invalidate="campaigns"/><DeleteButton run={()=>contentApi.deleteCampaign(r.id)} invalidate="campaigns"/></div>} ]}/></section></div></Page>}
export const ContentOverviewPage=()=>{const products=useData("products",contentApi.products),news=useData("news",contentApi.news),campaigns=useData("campaigns",contentApi.campaigns);return <Page title="Kontent idarəetməsi" subtitle="Xəbər, məhsul və kampaniya xülasəsi"><div className="grid"><Metric label="Məhsul" value={products.data?.length??0}/><Metric label="Xəbər" value={news.data?.length??0}/><Metric label="Kampaniya" value={campaigns.data?.length??0}/></div></Page>};
function CrudForm({title,form,setForm,onSubmit}:{title:string;form:any;setForm:(x:any)=>void;onSubmit:()=>void}){return <form className="card form" onSubmit={(event:FormEvent)=>{event.preventDefault();onSubmit()}}><h2>{title}</h2>{Object.entries(form).filter(([key])=>key!=="branch_id").map(([key,value])=><label className="field" key={key}>{key.replaceAll("_"," ")}<input type={key.includes("_on")?"date":typeof value==="number"?"number":"text"} value={String(value??"")} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<button className="btn">Yadda saxla</button></form>}
function DeleteButton({run,invalidate}:{run:()=>Promise<void>;invalidate:string}){const client=useQueryClient(),mutation=useMutation({mutationFn:run,onSuccess:()=>client.invalidateQueries({queryKey:[invalidate]})});return <button className="btn danger small" onClick={()=>mutation.mutate()}>Sil</button>}
function EditButton({run,invalidate}:{run:()=>Promise<any>;invalidate:string}){const client=useQueryClient(),mutation=useMutation({mutationFn:run,onSuccess:()=>client.invalidateQueries({queryKey:[invalidate]})});return <button className="btn secondary small" onClick={()=>mutation.mutate()}>Redaktə</button>}
function Select({label,value,options,onChange}:{label:string;value:string;options:any[];onChange:(x:string)=>void}){return <label className="field">{label}<select value={value} onChange={e=>onChange(e.target.value)}><option value="">Seçin</option>{options.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label>}
