import { useEffect, useRef, useState } from "react";
import { Alert, Image, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { CameraView, useCameraPermissions } from "expo-camera";
import { useMutation, useQuery } from "@tanstack/react-query";
import { api, uploadAsset } from "../services/api";
import { Button, Card, PageTitle, Screen, State } from "../components/ui";
import { colors } from "../constants/theme";

const categories=[["PRODUCT","Məhsul"],["PRICE","Qiymət uyğunsuzluğu"],["SHELF","Rəf və stok"],["CLEANLINESS","Təmizlik"],["SAFETY","Təhlükəsizlik"],["CUSTOMER_SERVICE","Xidmət"],["OTHER","Digər"]] as const;
export default function Report(){
  const params=useLocalSearchParams<{category?:string;title?:string;description?:string;barcode?:string}>();
  const [title,setTitle]=useState(params.title??""),[description,setDescription]=useState(params.description??""),[category,setCategory]=useState(params.category??""),[branchId,setBranchId]=useState(""),[step,setStep]=useState(1),[photoUri,setPhotoUri]=useState(""),[attachmentId,setAttachmentId]=useState(""),[cameraOpen,setCameraOpen]=useState(false),[uploading,setUploading]=useState(false),[aiResult,setAiResult]=useState<any>();
  const [permission,requestPermission]=useCameraPermissions();const camera=useRef<CameraView>(null);
  const branches=useQuery({queryKey:["branches"],queryFn:api.branches});
  useEffect(()=>{if(!branchId&&branches.data?.[0])setBranchId(branches.data[0].id)},[branchId,branches.data]);
  const review=useMutation({mutationFn:()=>api.reviewReport({title,description,category}),onSuccess:(result)=>{setAiResult(result);setStep(3)},onError:(error)=>Alert.alert("AI yoxlaması alınmadı",error.message)});
  const submit=useMutation({mutationFn:()=>api.createReport({branch_id:branchId,category:aiResult?.suggested_category??category,title,description:params.barcode?`${description}\nBarkod: ${params.barcode}`:description,attachment_ids:attachmentId?[attachmentId]:[]}),onSuccess:(report)=>{Alert.alert("Müraciət göndərildi",`İzləmə nömrəsi: ${report.tracking_number}`);router.replace({pathname:"/report-detail",params:{id:report.id}})}});
  async function openCamera(){if(!permission?.granted){const result=await requestPermission();if(!result.granted){Alert.alert("Kamera icazəsi lazımdır","Problemin şəklini birbaşa çəkmək üçün kamera icazəsi verin.");return}}setCameraOpen(true)}
  async function capture(){const picture=await camera.current?.takePictureAsync({quality:.72});if(!picture)return;setCameraOpen(false);setPhotoUri(picture.uri);setUploading(true);try{const asset=await uploadAsset(picture.uri,"image/jpeg");setAttachmentId(asset.id)}catch(error){Alert.alert("Şəkil göndərilmədi",error instanceof Error?error.message:"Yenidən çəkin.");setPhotoUri("")}finally{setUploading(false)}}
  const chosenBranch=branches.data?.find((branch:any)=>branch.id===branchId);
  if(cameraOpen)return <View style={s.cameraPage}><CameraView ref={camera} style={StyleSheet.absoluteFill} facing="back"/><View style={s.cameraOverlay}><Text style={s.cameraHelp}>Problemi aydın şəkildə çərçivəyə alın</Text><Pressable style={s.shutter} onPress={capture}><View style={s.shutterInner}/></Pressable><Button secondary title="Ləğv et" onPress={()=>setCameraOpen(false)}/></View></View>;
  return <Screen><Text style={s.progress}>ADDIM {step}/3</Text><PageTitle title={step===1?"Kateqoriya və filial":step===2?"Problemi göstərin":"AI yoxlaması və təsdiq"} subtitle="AI yalnız kateqoriya və prioritet təklif edir; son yoxlamanı filial əməkdaşı aparır."/><State loading={branches.isLoading} error={branches.isError}/>
    {step===1&&<><Text style={s.label}>Problem kateqoriyası</Text><View style={s.chips}>{categories.map(([value,label])=><Pressable key={value} onPress={()=>setCategory(value)} style={[s.chip,category===value&&s.chipActive]}><Text style={category===value&&s.chipTextActive}>{label}</Text></Pressable>)}</View><Text style={s.label}>Filial</Text>{branches.data?.map((branch:any)=><Pressable key={branch.id} onPress={()=>setBranchId(branch.id)}><Card><View style={s.branchRow}><View style={s.radio}>{branchId===branch.id&&<View style={s.radioDot}/>}</View><View style={{flex:1}}><Text style={s.branchName}>{branch.name}</Text><Text style={s.meta}>{branch.address}</Text></View></View></Card></Pressable>)}<Button disabled={!category||!branchId} title="Davam et" onPress={()=>setStep(2)}/></>}
    {step===2&&<><TextInput style={s.input} placeholder="Qısa başlıq" value={title} onChangeText={setTitle}/><TextInput style={[s.input,s.multiline]} multiline placeholder="Nə baş verdi? Yer və məhsul detallarını yazın." value={description} onChangeText={setDescription}/>{params.barcode&&<Text style={s.prefill}>Məhsul barkodu: {params.barcode}</Text>}{photoUri?<Card><Image source={{uri:photoUri}} style={s.preview}/><Text style={s.success}>{uploading?"Şəkil göndərilir…":"✓ Şəkil müraciətə əlavə edildi"}</Text><Button secondary title="Şəkli yenidən çək" onPress={openCamera}/></Card>:<Pressable style={s.cameraAction} onPress={openCamera}><Text style={s.cameraIcon}>📷</Text><Text style={s.cameraActionTitle}>Problemin şəklini çək</Text><Text style={s.meta}>Qalereyadan yükləmə yoxdur — kamera birbaşa açılır</Text></Pressable>}<Button disabled={title.trim().length<4||description.trim().length<10||uploading||!attachmentId||review.isPending} title={review.isPending?"AI yoxlayır…":"AI yoxlamasından keç"} onPress={()=>review.mutate()}/><Text style={s.requirement}>Davam etmək üçün başlıq, ətraflı təsvir və kamera şəkli tələb olunur.</Text><Button secondary title="Geri" onPress={()=>setStep(1)}/></>}
    {step===3&&<><Card><Text style={s.aiTitle}>✦ AI dəstəkli ilkin yoxlama</Text><Text>{aiResult?.summary}</Text><View style={s.aiRow}><Text style={s.meta}>Təklif olunan kateqoriya</Text><Text style={s.aiValue}>{aiResult?.suggested_category}</Text></View><View style={s.aiRow}><Text style={s.meta}>Təklif olunan prioritet</Text><Text style={s.aiValue}>{aiResult?.suggested_priority}</Text></View>{aiResult?.warnings?.map((warning:string)=><Text key={warning} style={s.warning}>⚠ {warning}</Text>)}<Text style={s.human}>İnsan təsdiqi mütləqdir</Text></Card><Card><Text style={s.cardTitle}>{title}</Text><Text>{description}</Text><Text style={s.meta}>Filial: {chosenBranch?.name}</Text>{photoUri&&<Image source={{uri:photoUri}} style={s.preview}/>} {submit.error&&<Text style={s.error}>{submit.error.message}</Text>}<Button disabled={submit.isPending} title={submit.isPending?"Göndərilir…":"Problemi bildir"} onPress={()=>submit.mutate()}/><Button secondary title="Düzəliş et" onPress={()=>setStep(2)}/></Card></>}
  </Screen>;
}
const s=StyleSheet.create({progress:{color:colors.blue,fontWeight:"900"},label:{fontWeight:"900",color:colors.navy},chips:{flexDirection:"row",flexWrap:"wrap",gap:8},chip:{paddingHorizontal:13,paddingVertical:11,borderRadius:999,borderWidth:1,borderColor:colors.border,backgroundColor:"white"},chipActive:{borderColor:colors.blue,backgroundColor:colors.softBlue},chipTextActive:{color:colors.blue,fontWeight:"800"},branchRow:{flexDirection:"row",alignItems:"center",gap:12},radio:{width:22,height:22,borderRadius:11,borderWidth:2,borderColor:colors.blue,alignItems:"center",justifyContent:"center"},radioDot:{width:10,height:10,borderRadius:5,backgroundColor:colors.blue},branchName:{fontWeight:"900",color:colors.navy},meta:{color:colors.muted},input:{backgroundColor:"white",borderWidth:1,borderColor:colors.border,borderRadius:13,padding:15},multiline:{height:130,textAlignVertical:"top"},prefill:{color:colors.blue,fontWeight:"700"},cameraAction:{minHeight:150,borderWidth:1,borderStyle:"dashed",borderColor:colors.blue,borderRadius:16,backgroundColor:colors.softBlue,alignItems:"center",justifyContent:"center",padding:18},cameraIcon:{fontSize:34},cameraActionTitle:{fontWeight:"900",fontSize:17,color:colors.blue},preview:{width:"100%",height:190,borderRadius:12},success:{color:colors.green,fontWeight:"800"},requirement:{fontSize:12,color:colors.muted,textAlign:"center"},aiTitle:{fontSize:18,fontWeight:"900",color:colors.blue},aiRow:{flexDirection:"row",justifyContent:"space-between"},aiValue:{fontWeight:"900",color:colors.navy},warning:{color:"#9a6200"},human:{color:colors.green,fontWeight:"900"},cardTitle:{fontSize:19,fontWeight:"900"},error:{color:colors.red},cameraPage:{flex:1,backgroundColor:"black"},cameraOverlay:{position:"absolute",left:20,right:20,bottom:35,alignItems:"center",gap:16},cameraHelp:{color:"white",fontWeight:"800",backgroundColor:"#0009",padding:10,borderRadius:10},shutter:{width:76,height:76,borderRadius:38,borderWidth:4,borderColor:"white",alignItems:"center",justifyContent:"center"},shutterInner:{width:58,height:58,borderRadius:29,backgroundColor:"white"}});
