import {useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {Link,useNavigate,useParams} from "react-router-dom";
import {operationsApi,session} from "../../services/api";
import {DataTable,DetailLink,Loading,MediaViewer,Metric,MiniChart,Page,StatusBadge,Timeline} from "../../components/ui";

const useData=(key:string,fn:()=>Promise<any>)=>useQuery({queryKey:[key],queryFn:fn});
export function BranchDashboard(){const dashboard=useData("dashboard",operationsApi.dashboard),incidents=useData("incidents",operationsApi.incidents),audits=useData("audits",operationsApi.audits);if(dashboard.isLoading)return <Loading/>;return <Page title="Filial dashboard" subtitle="Cari filialın report, incident və audit göstəriciləri"><div className="grid"><Metric label="Açıq hadisə" value={dashboard.data.open_incidents}/><Metric label="Yüksək risk" value={dashboard.data.high_risk}/><Metric label="Həll edilib" value={dashboard.data.resolved}/><Metric label="Smart Store Score" value={`${dashboard.data.smart_store_score}/100`}/></div><div className="content spaced"><section className="card"><h2>Son hadisələr</h2><DataTable rows={(incidents.data??[]).slice(0,6)} columns={[{key:"title",label:"Hadisə",render:r=><DetailLink to={`/branch/incidents/${r.id}`} label={r.title}/>},{key:"source",label:"Mənbə"},{key:"status",label:"Status",render:r=><StatusBadge value={r.status}/>} ]}/></section><section className="card"><h2>Audit statusları</h2><MiniChart rows={Object.entries((audits.data??[]).reduce((a:any,x:any)=>({...a,[x.status]:(a[x.status]??0)+1}),{})).map(([status,count])=>({status,count}))} labelKey="status" valueKey="count"/></section></div></Page>}

export function ReportsPage(){const q=useData("reports",operationsApi.reports);return <Page title="Müştəri reportları" subtitle="Yalnız bu filiala göndərilmiş müraciətlər"><section className="card">{q.isLoading?<Loading/>:<DataTable rows={q.data??[]} columns={[{key:"tracking_number",label:"İzləmə"},{key:"title",label:"Başlıq",render:r=><DetailLink to={`/branch/reports/${r.id}`} label={r.title}/>},{key:"category",label:"Kateqoriya"},{key:"status",label:"Status",render:r=><StatusBadge value={r.status}/>},{key:"created_at",label:"Tarix",render:r=>new Date(r.created_at).toLocaleString("az-AZ")} ]}/>}</section></Page>}
export function ReportDetailPage(){const{id}=useParams(),q=useQuery({queryKey:["report",id],queryFn:()=>operationsApi.report(id!)});if(q.isLoading)return <Loading/>;if(q.error)return <Loading error={q.error}/>;return <Page title={q.data.title} subtitle={`${q.data.tracking_number} · ${q.data.category}`}><div className="case"><section className="card"><StatusBadge value={q.data.status}/><h2>Təsvir</h2><p>{q.data.description}</p><MediaViewer media={q.data.media}/></section><aside className="card"><h2>Report məlumatları</h2><p><b>Barkod:</b> {q.data.barcode??"—"}</p><p><b>Alt kateqoriya:</b> {q.data.subcategory??"—"}</p><Link className="btn secondary" to="/branch/reports">Geri</Link></aside></div></Page>}

export function SuggestionsPage(){const client=useQueryClient(),q=useData("suggestions",operationsApi.suggestions),mutation=useMutation({mutationFn:({id,status}:{id:string;status:string})=>operationsApi.updateSuggestion(id,status,"Filial rəhbərliyi tərəfindən yeniləndi."),onSuccess:()=>client.invalidateQueries({queryKey:["suggestions"]})});return <Page title="Rəhbərliyə təkliflər" subtitle="Filial və ümumi organisation təklifləri"><section className="card"><DataTable rows={q.data??[]} columns={[{key:"tracking_number",label:"İzləmə"},{key:"title",label:"Təklif"},{key:"category",label:"Kateqoriya"},{key:"status",label:"Status",render:r=><StatusBadge value={r.status}/>},{key:"actions",label:"Əməliyyat",render:r=><div className="inline"><button className="btn small" onClick={()=>mutation.mutate({id:r.id,status:"UNDER_REVIEW"})}>Baxışa al</button><button className="btn secondary small" onClick={()=>mutation.mutate({id:r.id,status:"PLANNED"})}>Planla</button></div>} ]}/></section></Page>}

export function IncidentsPage({all=false}:{all?:boolean}){const q=useData("incidents",operationsApi.incidents);return <Page title={all?"Bütün incidentlər":"Filial incidentləri"} subtitle="Müştəri, audit və kamera mənbələrinin vahid axını"><section className="card"><DataTable rows={q.data??[]} columns={[{key:"title",label:"Hadisə",render:r=><DetailLink to={`${all?"/head":"/branch"}/incidents/${r.id}`} label={r.title}/>},{key:"source",label:"Mənbə"},{key:"priority",label:"Prioritet",render:r=><StatusBadge value={r.priority}/>},{key:"status",label:"Status",render:r=><StatusBadge value={r.status}/>},{key:"created_at",label:"Tarix",render:r=>new Date(r.created_at).toLocaleString("az-AZ")} ]}/></section></Page>}
export function IncidentDetailPage({base="/branch"}:{base?:string}){
  const{id}=useParams(),navigate=useNavigate(),client=useQueryClient(),q=useData("incidents",operationsApi.incidents),item=q.data?.find((row:any)=>row.id===id),[note,setNote]=useState(""),[customerVisible,setCustomerVisible]=useState(false);
  const transition=useMutation({mutationFn:(status:string)=>{const body:any={status,internal_note:`${status.replaceAll("_"," ")} transition completed by admin.`,customer_note:`Müraciət statusu yeniləndi: ${status.replaceAll("_"," ")}.`};if(status==="ASSIGNED")Object.assign(body,{responsible_department:prompt("Məsul şöbə","Operations")||"Operations",assigned_admin_id:session.user()?.id,sla_hours:24});if(status==="REJECTED")body.rejection_reason=prompt("Rədd səbəbi")||"Evidence was insufficient.";if(status==="MANUALLY_RESOLVED")body.resolution_reason=prompt("Həll səbəbi")||"Resolution verified by administrator.";if(status==="REOPENED")body.reopening_reason=prompt("Yenidən açılma səbəbi")||"New evidence received.";return operationsApi.updateIncident(id!,body)},onSuccess:()=>client.invalidateQueries({queryKey:["incidents"]})});
  const addNote=useMutation({mutationFn:()=>operationsApi.addIncidentNote(id!,note,customerVisible),onSuccess:()=>{setNote("");client.invalidateQueries({queryKey:["incidents"]})}});
  if(!item)return <Loading error={q.error}/>;
  return <Page title={item.title} subtitle={`${item.source} · ${item.category}`}><div className="case"><section className="card"><div className="inline"><StatusBadge value={item.priority}/><StatusBadge value={item.status}/>{item.is_overdue?<StatusBadge value="OVERDUE"/>:null}</div><p>{item.description}</p><MediaViewer media={item.attachments}/><h2>Status tarixçəsi</h2><Timeline items={item.history}/><h2>Qeydlər</h2>{item.notes?.map((entry:any)=><div className="event" key={entry.id}><StatusBadge value={entry.visibility}/><p>{entry.note}</p></div>)}<label className="field">Yeni qeyd<textarea value={note} onChange={event=>setNote(event.target.value)}/></label><label className="check"><input type="checkbox" checked={customerVisible} onChange={event=>setCustomerVisible(event.target.checked)}/> Müştəriyə görünür</label><button className="btn" disabled={note.length<2} onClick={()=>addNote.mutate()}>Qeyd əlavə et</button></section><aside className="card"><h2>Lifecycle</h2><p><b>Şöbə:</b> {item.responsible_department??"—"}</p><p><b>SLA:</b> {item.sla_due_at?new Date(item.sla_due_at).toLocaleString("az-AZ"):"—"}</p><p><b>Staff:</b> {item.assigned_staff_id??"—"}</p><p><b>Admin:</b> {item.assigned_admin_id??"—"}</p>{item.rejection_reason?<p><b>Rədd:</b> {item.rejection_reason}</p>:null}{item.resolution_reason?<p><b>Həll:</b> {item.resolution_reason} ({item.resolution_actor_type})</p>:null}{item.reopening_reason?<p><b>Yenidən açılma:</b> {item.reopening_reason}</p>:null}{item.allowed_transitions.map((status:string)=><button className="btn action" key={status} onClick={()=>transition.mutate(status)}>{status.replaceAll("_"," ")}</button>)}{transition.error?<p className="error">{transition.error.message}</p>:null}<button className="btn secondary action" onClick={()=>navigate(`${base}/incidents`)}>Geri</button></aside></div></Page>}

function SimpleResource({title,subtitle,queryKey,queryFn,columns}:{title:string;subtitle:string;queryKey:string;queryFn:()=>Promise<any[]>;columns:Array<{key:string;label:string;render?:(r:any)=>any}>}){const q=useData(queryKey,queryFn);return <Page title={title} subtitle={subtitle}><section className="card">{q.isLoading?<Loading/>:<DataTable rows={q.data??[]} columns={columns}/>}</section></Page>}
export const StaffAuditsPage=()=> <SimpleResource title="Staff auditləri" subtitle="Tapşırıq, progress və completion vaxtları" queryKey="audits" queryFn={operationsApi.audits} columns={[{key:"title",label:"Tapşırıq"},{key:"priority",label:"Prioritet"},{key:"status",label:"Status",render:r=><StatusBadge value={r.status}/>},{key:"item_count",label:"Məhsul",render:r=>`${r.item_count}/${r.required_count}`},{key:"due_at",label:"Son vaxt",render:r=>new Date(r.due_at).toLocaleString("az-AZ")} ]}/>;
export const QualityFlagsPage=()=> <SimpleResource title="Audit keyfiyyət flagları" subtitle="Proses nəzarəti; avtomatik intizam qərarı deyil" queryKey="flags" queryFn={operationsApi.flags} columns={[{key:"code",label:"Kod"},{key:"message",label:"İzah"},{key:"severity",label:"Səviyyə",render:r=><StatusBadge value={r.severity}/>},{key:"created_at",label:"Tarix",render:r=>new Date(r.created_at).toLocaleString("az-AZ")} ]}/>;
export const ReAuditsPage=()=> <SimpleResource title="Təkrar auditlər" subtitle="İlkin və təkrar nəticələrin uyğunluğu" queryKey="reaudits" queryFn={operationsApi.reaudits} columns={[{key:"original_condition",label:"İlkin"},{key:"re_audit_condition",label:"Təkrar"},{key:"status",label:"Status",render:r=><StatusBadge value={r.status}/>},{key:"consistent",label:"Uyğunluq",render:r=>r.consistent==null?"Gözləyir":r.consistent?"Uyğundur":"Mismatch"} ]}/>;
export const CamerasPage=()=> <SimpleResource title="Filial kameraları" subtitle="Kamera mənbələri və aktivlik" queryKey="cameras" queryFn={operationsApi.cameras} columns={[{key:"name",label:"Kamera"},{key:"source_type",label:"Mənbə"},{key:"enabled",label:"Aktiv",render:r=>r.enabled?"Bəli":"Xeyr"},{key:"last_error",label:"Xəta"}]}/>;
export const CameraEventsPage=()=> <SimpleResource title="Kamera hadisələri" subtitle="AI tapıntıları insan yoxlaması tələb edir" queryKey="camera-events" queryFn={operationsApi.cameraEvents} columns={[{key:"rule",label:"Qayda"},{key:"detected_frames",label:"Kadr"},{key:"created_at",label:"Tarix",render:r=>new Date(r.created_at).toLocaleString("az-AZ")}]}/>;
export const BranchStaffPage=()=> <SimpleResource title="Filial əməkdaşları" subtitle="Bu filiala bağlı STAFF hesabları" queryKey="staff" queryFn={operationsApi.staff} columns={[{key:"full_name",label:"Ad"},{key:"email",label:"E-poçt"},{key:"is_active",label:"Aktiv",render:r=>r.is_active?"Bəli":"Xeyr"}]}/>;
export function BranchSettingsPage(){const client=useQueryClient(),q=useData("branches",operationsApi.branches),branch=q.data?.[0],mutation=useMutation({mutationFn:(form:any)=>operationsApi.updateBranch(branch.id,form),onSuccess:()=>client.invalidateQueries({queryKey:["branches"]})});if(!branch)return <Loading/>;return <Page title="Filial ayarları" subtitle="Ad, ünvan, iş saatı və açıq status"><BranchForm initial={branch} onSave={value=>mutation.mutate(value)}/></Page>}
function BranchForm({initial,onSave}:{initial:any;onSave:(v:any)=>void}){const[form,setForm]=useState({name:initial.name,address:initial.address,hours:initial.hours,is_open:initial.is_open});return <form className="card form" onSubmit={event=>{event.preventDefault();onSave(form)}}>{["name","address","hours"].map(key=><label className="field" key={key}>{key}<input value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label className="check"><input type="checkbox" checked={form.is_open} onChange={e=>setForm({...form,is_open:e.target.checked})}/> Filial açıqdır</label><button className="btn">Yadda saxla</button></form>}
