import * as SecureStore from "expo-secure-store";
const root=process.env.EXPO_PUBLIC_API_URL??"http://localhost:8000/api/v1";
let sessionAuthenticated=false;
export type HomeData={user:{full_name:string};selected_branch:any;news:any[];products:any[];discounts:any[];branches:any[];loyalty:any;reports:any[]};

async function request<T>(path:string,init?:RequestInit,retry=true):Promise<T>{
  if(!sessionAuthenticated)throw new Error("LOGIN_REQUIRED");
  const token=await SecureStore.getItemAsync("token");
  const response=await fetch(root+path,{...init,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,...init?.headers}});
  if(response.status===401&&retry){const refresh=await SecureStore.getItemAsync("refresh_token");if(refresh){const renewed=await fetch(root+"/auth/refresh",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({refresh_token:refresh})});if(renewed.ok){const data=await renewed.json();await SecureStore.setItemAsync("token",data.access_token);await SecureStore.setItemAsync("refresh_token",data.refresh_token);return request<T>(path,init,false)}}}
  if(!response.ok){let detail="Sorğu alınmadı";try{detail=(await response.json()).detail??detail}catch{}throw new Error(detail)}
  return response.status===204?undefined as T:response.json();
}
async function storeSession(data:any){sessionAuthenticated=true;await SecureStore.setItemAsync("token",data.access_token);await SecureStore.setItemAsync("refresh_token",data.refresh_token);return data.user}
export async function demoLogin(){const response=await fetch(root+"/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:"customer@demo.az",password:"Demo123!"})});if(!response.ok)throw new Error("Demo giriş alınmadı");const data=await response.json();await storeSession(data);return data}
export async function login(email:string,password:string){const response=await fetch(root+"/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});if(!response.ok)throw new Error("E-poçt və ya şifrə yanlışdır");return storeSession(await response.json())}
export async function register(body:any){const response=await fetch(root+"/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!response.ok)throw new Error((await response.json()).detail??"Qeydiyyat alınmadı");return storeSession(await response.json())}
export async function logout(){try{await request("/auth/logout",{method:"POST"},false)}finally{sessionAuthenticated=false;await SecureStore.deleteItemAsync("token");await SecureStore.deleteItemAsync("refresh_token")}}

export async function selectedBranchId(){return SecureStore.getItemAsync("selected_branch_id")}
export async function selectBranch(id:string){await SecureStore.setItemAsync("selected_branch_id",id)}
export const api={home:async()=>{const id=await selectedBranchId();return request<HomeData>(`/home${id?`?branch_id=${id}`:""}`)},reports:()=>request<any[]>("/reports"),branches:()=>request<any[]>("/branches"),reviewReport:(body:any)=>request<any>("/reports/ai-review",{method:"POST",body:JSON.stringify(body)}),createReport:(body:any)=>request<any>("/reports",{method:"POST",body:JSON.stringify(body)})};
export const customerApi={products:(q="")=>request<any[]>(`/products?q=${encodeURIComponent(q)}`),product:(id:string)=>request<any>(`/products/${id}`),barcode:(code:string)=>request<any>(`/products/barcode/${code}`),branch:(id:string)=>request<any>(`/branches/${id}`),discounts:()=>request<any[]>("/discounts"),discount:(id:string)=>request<any>(`/discounts/${id}`),favourites:()=>request<any[]>("/favourites/products"),favourite:(id:string)=>request(`/favourites/products/${id}`,{method:"POST"}),unfavourite:(id:string)=>request(`/favourites/products/${id}`,{method:"DELETE"}),news:()=>request<any[]>("/news"),newsDetail:(id:string)=>request<any>(`/news/${id}`),suggestions:()=>request<any[]>("/suggestions"),createSuggestion:(body:any)=>request<any>("/suggestions",{method:"POST",body:JSON.stringify(body)}),notifications:()=>request<any[]>("/notifications"),readNotification:(id:string)=>request(`/notifications/${id}/read`,{method:"PATCH"}),readAllNotifications:()=>request<{updated:number}>("/notifications/read-all",{method:"PATCH"}),me:()=>request<any>("/auth/me"),updateProfile:(body:any)=>request<any>("/profile",{method:"PATCH",body:JSON.stringify(body)}),deleteRequest:(reason:string)=>request("/profile/delete-request",{method:"POST",body:JSON.stringify({reason})}),cards:()=>request<any[]>("/loyalty/cards"),transactions:(id:string)=>request<any[]>(`/loyalty/cards/${id}/transactions`)};
export const staffApi={audits:()=>request<any[]>("/staff/audits"),quality:()=>request<any>("/staff/quality-summary"),reAudits:()=>request<any[]>("/staff/re-audits"),completeReAudit:(id:string,condition:string)=>request<any>(`/staff/re-audits/${id}/complete`,{method:"POST",body:JSON.stringify({condition})}),start:(id:string)=>request<any>(`/staff/audits/${id}/start`,{method:"POST"}),addItem:(id:string,body:any)=>request<any>(`/staff/audits/${id}/items`,{method:"POST",body:JSON.stringify(body)}),complete:(id:string)=>request<any>(`/staff/audits/${id}/complete`,{method:"POST"}),ocr:(demo_text:string)=>request<any>("/ocr/date-candidates",{method:"POST",body:JSON.stringify({demo_text})})};
export async function uploadImage(uri:string,path="/ocr/image"){const token=await SecureStore.getItemAsync("token");const body=new FormData();body.append("file",{uri,name:"capture.jpg",type:"image/jpeg"} as any);const response=await fetch(root+path,{method:"POST",headers:{Authorization:`Bearer ${token}`},body});if(!response.ok)throw new Error((await response.json()).detail??"Şəkil göndərilmədi");return response.json()}
export async function uploadAsset(uri:string,type="image/jpeg"){const token=await SecureStore.getItemAsync("token");const body=new FormData();body.append("file",{uri,name:"camera-evidence.jpg",type} as any);const response=await fetch(root+"/uploads",{method:"POST",headers:{Authorization:`Bearer ${token}`},body});if(!response.ok)throw new Error((await response.json()).detail??"Şəkil göndərilmədi");return response.json()}
