import {ReactNode} from "react";
import {Link} from "react-router-dom";

export function Page({title,subtitle,children,actions}:{title:string;subtitle:string;children:ReactNode;actions?:ReactNode}){return <><header className="top"><div><h1>{title}</h1><p className="muted">{subtitle}</p></div>{actions}</header>{children}</>}
export function Loading({error}:{error?:unknown}){return <div className={error?"card error":"card muted"}>{error?"Məlumat yüklənmədi.":"Yüklənir…"}</div>}
export function StatusBadge({value}:{value:string}){return <span className={`badge ${value}`}>{value.replaceAll("_"," ")}</span>}
export function Metric({label,value,hint}:{label:string;value:string|number;hint?:string}){return <div className="card stat"><span className="muted">{label}</span><strong>{value}</strong>{hint?<small className="muted">{hint}</small>:null}</div>}
export function DataTable({columns,rows,empty="Məlumat yoxdur"}:{columns:Array<{key:string;label:string;render?:(row:any)=>ReactNode}>;rows:any[];empty?:string}){return <div className="table-wrap"><table><thead><tr>{columns.map(column=><th key={column.key}>{column.label}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={row.id??index}>{columns.map(column=><td key={column.key}>{column.render?column.render(row):String(row[column.key]??"—")}</td>)}</tr>)}</tbody></table>{!rows.length?<p className="muted empty">{empty}</p>:null}</div>}
export function Timeline({items}:{items:Array<{status?:string;note?:string;created_at:string}>}){return <div className="timeline">{items.map((item,index)=><div className="event" key={index}>{item.status?<StatusBadge value={item.status}/>:null}<p>{item.note}</p><small className="muted">{new Date(item.created_at).toLocaleString("az-AZ")}</small></div>)}</div>}
export function MiniChart({rows,labelKey,valueKey}:{rows:any[];labelKey:string;valueKey:string}){const max=Math.max(1,...rows.map(row=>Number(row[valueKey])));return <div className="chart">{rows.map(row=><div className="chart-row" key={row.id??row[labelKey]}><span>{row[labelKey]}</span><div className="chart-track"><div className="chart-fill" style={{width:`${Number(row[valueKey])/max*100}%`}}/></div><b>{row[valueKey]}</b></div>)}</div>}
export function MediaViewer({media=[]}:{media?:Array<{url:string;mime_type:string;name:string}>}){return <div className="media-grid">{media.map(item=>item.mime_type.startsWith("image/")?<a href={item.url} target="_blank" key={item.url}><img src={item.url} alt={item.name}/></a>:<a className="card" href={item.url} target="_blank" key={item.url}>{item.name}</a>)}</div>}
export const DetailLink=({to,label}:{to:string;label:string})=><Link className="table-link" to={to}>{label}</Link>;
