import{ReactNode}from"react";import{Image,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View}from"react-native";import{Ionicons}from"@expo/vector-icons";import{SafeAreaView}from"react-native-safe-area-context";import{colors}from"../constants/theme";import{mediaUrl}from"../services/api";import{useI18n}from"../services/i18n";
export function Screen({children,refreshing=false,onRefresh}:{children:ReactNode;refreshing?:boolean;onRefresh?:()=>void}){return <SafeAreaView style={s.safe} edges={["top","left","right"]}><ScrollView keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} contentContainerStyle={s.screen} refreshControl={onRefresh?<RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor={colors.blue}/>:undefined}>{children}</ScrollView></SafeAreaView>}
export function PageTitle({title,subtitle,action}:{title:string;subtitle?:string;action?:ReactNode}){return <View style={s.titleRow}><View style={{flex:1}}><Text style={s.title}>{title}</Text>{subtitle?<Text style={s.muted}>{subtitle}</Text>:null}</View>{action}</View>}
export function Card({children,onPress}:{children:ReactNode;onPress?:()=>void}){const body=<View style={s.card}>{children}</View>;return onPress?<Pressable onPress={onPress}>{body}</Pressable>:body}
export function Button({title,onPress,disabled=false,secondary=false,icon}:{title:string;onPress:()=>void;disabled?:boolean;secondary?:boolean;icon?:keyof typeof Ionicons.glyphMap}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={({pressed})=>[s.button,secondary&&s.secondary,(disabled||pressed)&&{opacity:.55}]}>{icon?<Ionicons name={icon} size={19} color={secondary?colors.blue:"white"}/>:null}<Text style={[s.buttonText,secondary&&{color:colors.blue}]}>{title}</Text></Pressable>}
export function State({loading,error,empty,retry}:{loading?:boolean;error?:boolean;empty?:string;retry?:()=>void}){const{t}=useI18n();if(loading)return <View style={s.state}><Skeleton/><Skeleton/><Skeleton/></View>;if(error)return <View style={s.state}><Ionicons name="cloud-offline-outline" size={34} color={colors.muted}/><Text style={s.muted}>{t("loadError")}</Text>{retry?<Button secondary title={t("retry")} onPress={retry}/>:null}</View>;if(empty)return <View style={s.state}><Ionicons name="file-tray-outline" size={34} color={colors.muted}/><Text style={s.muted}>{empty}</Text></View>;return null}
export function Skeleton(){return <View style={s.skeleton}/>}export function Status({value}:{value:string}){const{t}=useI18n();const key:Record<string,Parameters<typeof t>[0]>={SUBMITTED:"statusSubmitted",RECEIVED:"statusSubmitted",NEW:"statusSubmitted",PRECHECK:"statusReview",UNDER_REVIEW:"statusReview",CONFIRMED:"statusReview",PLANNED:"statusPlanned",IMPLEMENTED:"statusImplemented",REJECTED:"statusRejected",VERIFICATION_REQUIRED:"statusVerification",VERIFIED:"statusReview",ASSIGNED:"statusReview",REOPENED:"statusReview",IN_PROGRESS:"statusProgress",RESOLUTION_CANDIDATE:"statusProgress",RESOLVED:"statusResolved",MANUALLY_RESOLVED:"statusResolved",AUTO_RESOLVED:"statusResolved"};return <Text style={s.badge}>{key[value]?t(key[value]):value.replaceAll("_"," ")}</Text>}
export function RemoteImage({url,height=150}:{url?:string;height?:number}){const source=mediaUrl(url),size=height===92?{width:92}:{width:"100%" as const};return source?<Image source={{uri:source}} style={[s.image,{height},size]}/>:<View style={[s.image,s.imageFallback,{height},size]}><Ionicons name="storefront-outline" size={42} color={colors.blue}/><Text style={s.assetMark}>MARTIQ RETAIL</Text></View>}
export function Chip({label,active=false,onPress}:{label:string;active?:boolean;onPress?:()=>void}){return <Pressable disabled={!onPress} onPress={onPress} style={[s.chip,active&&s.chipActive]}><Text style={[s.chipText,active&&s.chipTextActive]}>{label}</Text></Pressable>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},screen:{paddingHorizontal:18,paddingTop:12,paddingBottom:104,gap:15,backgroundColor:colors.background,minHeight:"100%"},titleRow:{flexDirection:"row",alignItems:"center",gap:12},title:{fontSize:26,fontWeight:"900",color:colors.navy},muted:{color:colors.muted,lineHeight:20},card:{padding:16,borderWidth:1,borderColor:colors.border,borderRadius:18,backgroundColor:"white",gap:9,overflow:"hidden",shadowColor:"#10213A",shadowOffset:{width:0,height:4},shadowOpacity:.04,shadowRadius:12,elevation:2},button:{minHeight:50,paddingHorizontal:15,borderRadius:14,backgroundColor:colors.blue,alignItems:"center",justifyContent:"center",flexDirection:"row",gap:8},secondary:{backgroundColor:colors.softBlue},buttonText:{fontWeight:"800",color:"white",textAlign:"center"},badge:{alignSelf:"flex-start",backgroundColor:colors.softAmber,color:"#8A5700",fontSize:11,fontWeight:"800",paddingVertical:6,paddingHorizontal:9,borderRadius:99},state:{paddingVertical:28,alignItems:"center",gap:12},skeleton:{height:82,width:"100%",borderRadius:16,backgroundColor:"#EAF0F7"},image:{width:"100%",borderRadius:15,backgroundColor:colors.softBlue},imageFallback:{alignItems:"center",justifyContent:"center",gap:7},assetMark:{fontSize:10,fontWeight:"900",letterSpacing:1.6,color:colors.blue},chip:{paddingVertical:9,paddingHorizontal:13,borderRadius:99,borderWidth:1,borderColor:colors.border,backgroundColor:"white"},chipActive:{backgroundColor:colors.blue,borderColor:colors.blue},chipText:{color:colors.muted,fontWeight:"700",fontSize:12},chipTextActive:{color:"white"}});
