export default {
  appName:"MARTIQ",continue:"Davam et",back:"Geri",retry:"Yenidən yoxla",save:"Yadda saxla",cancel:"Ləğv et",loading:"Yüklənir…",loadError:"Məlumatı yükləmək mümkün olmadı.",empty:"Məlumat tapılmadı",all:"Hamısı",open:"Açıq",closed:"Bağlı",selected:"Seçilib",favourite:"Seçilmişlərə əlavə et",unfavourite:"Seçilmişlərdən çıxar",details:"Ətraflı bax",search:"Axtar",currency:"₼",onboardingTitle:"Market təcrübəniz bir tətbiqdə",onboardingBody:"Qiymətləri yoxlayın, endirimləri izləyin və müraciətlərinizi rahat idarə edin.",onboardingSecure:"Təhlükəsiz hesab və şəffaf müraciət tarixçəsi",getStarted:"Başlayaq",welcome:"Xoş gəlmisiniz",loginSubtitle:"Market məlumatları, bonuslar və müraciətləriniz bir tətbiqdə.",email:"E-poçt ünvanı",password:"Şifrə",login:"Daxil ol",loggingIn:"Daxil olunur…",forgot:"Şifrəni unutmusunuz?",noAccount:"Hesabınız yoxdur?",register:"Qeydiyyatdan keçin",forgotTitle:"Şifrəni bərpa et",forgotBody:"E-poçtunuzu yazın. Hesab mövcuddursa, bərpa təlimatı göndəriləcək.",sendInstructions:"Təlimatı göndər",forgotSent:"Sorğu qəbul edildi",forgotSentBody:"Hesab mövcuddursa, bərpa təlimatı e-poçta göndəriləcək.",
  registerTitle:"Hesab yaradın",registerSubtitle:"MARTIQ xidmətlərindən təhlükəsiz istifadə edin",firstName:"Ad",lastName:"Soyad",phone:"Telefon",confirmPassword:"Şifrə təkrarı",market:"Market",acceptPrivacy:"Məxfilik şərtlərini qəbul edirəm",completeRegistration:"Qeydiyyatı tamamla",
  hello:"Salam",homeSubtitle:"Seçilmiş market və filial",change:"Dəyiş",news:"Xəbərlər",quickActions:"Sürətli keçidlər",checkPrice:"Qiyməti yoxla",discounts:"Endirimlər",reportProblem:"Problem bildir",sendSuggestion:"Təklif göndər",findBranch:"Filial tap",scanProduct:"Məhsul skan et",loyalty:"Bonus balansı",featuredDiscounts:"Seçilmiş endirimlər",activeReports:"Aktiv müraciətlər",nearbyBranches:"Yaxın və sevimli filiallar",seeAll:"Hamısına bax",noActiveReports:"Aktiv müraciətiniz yoxdur",monthlyEarned:"Bu ay qazanılıb",expiring:"Müddəti bitəcək",
  newsTitle:"Market xəbərləri",newsEmpty:"Hazırda yeni xəbər yoxdur",published:"Yayımlandı",allBranches:"Bütün filiallar",branchScope:"Filial xəbəri",marketScope:"Market xəbəri",
  productsTitle:"Məhsullar",productsSubtitle:"Seçilmiş filial üzrə qiymət və mövcudluq",productSearch:"Məhsul, brend və ya barkod",category:"Kateqoriya",sort:"Sıralama",sortName:"Ada görə",sortPriceAsc:"Ucuzdan bahaya",sortPriceDesc:"Bahadan ucuza",sortDiscount:"Endirimə görə",productsEmpty:"Məhsul tapılmadı",branchPrice:"Filial qiyməti",inStock:"Stokda var",outOfStock:"Stokda yoxdur",barcode:"Barkod",priceMismatch:"Qiymət uyğunsuzluğu bildir",scan:"Skan et",
  discountsTitle:"Endirim kampaniyaları",discountsSubtitle:"Aktiv təkliflər və iştirak edən filiallar",activeOnly:"Aktiv",savedOnly:"Seçilmiş",campaignPeriod:"Kampaniya müddəti",participatingBranches:"İştirak edən filiallar",discountProducts:"Endirimli məhsullar",noCampaigns:"Uyğun kampaniya yoxdur",
  branchesTitle:"Filiallar",branchesSubtitle:"Market və üstünlük verdiyiniz filialı seçin",selectBranch:"Bu filialı seç",preferredBranch:"Üstünlük verilən filial",services:"Xidmətlər",workingHours:"İş saatları",address:"Ünvan",distance:"Məsafə",noBranches:"Filial tapılmadı",
  reportsTitle:"Müraciətlərim",reportsSubtitle:"Problemlərin statusunu və tarixçəsini izləyin",newReport:"Yeni müraciət",reportWizard:"Problem bildirin",step:"Addım",chooseBranch:"Filialı seçin",chooseCategory:"Kateqoriyanı seçin",reportTitle:"Başlıq",reportTitleHint:"Problemi qısa adlandırın",description:"Ətraflı təsvir",descriptionHint:"Nə baş verdiyini, yeri və məhsul detallarını yazın",media:"Foto sübut",takePhoto:"Kamera ilə çək",choosePhoto:"Qalereyadan seç",uploading:"Yüklənir",uploadRetry:"Yenidən yüklə",aiReview:"Məlumatları yoxla",edit:"Düzəliş et",submit:"Göndər",submitting:"Göndərilir…",trackingNumber:"İzləmə nömrəsi",timeline:"Status tarixçəsi",rejectionReason:"İmtina səbəbi",resolutionNote:"Həll qeydi",mediaPreview:"Əlavə edilmiş media",noReports:"Hələ müraciət göndərməmisiniz",reportSent:"Müraciət göndərildi",humanReview:"Son qərarı filial əməkdaşı verir",categoryProduct:"Məhsul",categoryPrice:"Qiymət",categoryShelf:"Rəf və stok",categoryClean:"Təmizlik",categorySafety:"Təhlükəsizlik",categoryService:"Xidmət",categoryOther:"Digər",
  suggestionsTitle:"Rəhbərliyə təkliflər",suggestionsSubtitle:"İnkişaf təkliflərinizi göndərin və izləyin",suggestionTitle:"Təklifin başlığı",anonymous:"Anonim göndər",mySuggestions:"Təkliflərim",noSuggestions:"Hələ təklif yoxdur",managementNote:"Rəhbərlik qeydi",suggestionDetail:"Təklif detalları",
  cardsTitle:"Kart və bonuslar",simulated:"Simulyasiya edilmiş inteqrasiya — real market loyalty sistemi deyil",bonus:"bonus",cardHistory:"Bonus tarixçəsi",cardNumber:"Kart nömrəsi",expiringPoints:"Bitəcək bonuslar",noCards:"Loyalty kartı yoxdur",
  profile:"Profil",profileSubtitle:"Şəxsi məlumatlar və tətbiq seçimləri",fullName:"Ad və soyad",profileSaved:"Profil yeniləndi",chooseProfileImage:"Profil şəklini dəyiş",preferences:"Bildiriş seçimləri",privacy:"Məxfilik və hesab",language:"Dil",azerbaijani:"Azərbaycan dili",english:"English",logout:"Hesabdan çıx",deleteAccount:"Hesabın silinməsini istə",deleteReason:"Silmə səbəbi",deleteAccepted:"Hesabın silinməsi sorğusu qəbul edildi",confirmDelete:"Sorğunu göndərmək istədiyinizə əminsiniz?",
  notifications:"Bildirişlər",unread:"oxunmamış bildiriş",markAllRead:"Hamısını oxunmuş et",noNotifications:"Yeni bildiriş yoxdur",notificationNews:"Market xəbərləri",notificationDiscounts:"Endirimlər",notificationReports:"Problem statusu",notificationSuggestions:"Təklif statusu",notificationPoints:"Bitən bonuslar",notificationBranches:"Filial elanları",
  navHome:"Əsas",navPrices:"Məhsullar",navReport:"Bildir",navCards:"Kartlar",navProfile:"Profil",statusSubmitted:"Göndərildi",statusReview:"Baxılır",statusPlanned:"Planlaşdırılıb",statusImplemented:"Tətbiq edildi",statusRejected:"İmtina edildi",statusVerification:"Yoxlanılır",statusProgress:"İcradadır",statusResolved:"Həll edildi"
} as const;
